Лабораторна робота №2
з дисципліни "Нейронні мережі"

студента групи АнД-41

Айрапетова Давида

Завдання: Поглиблено вивчити функцію make_regression. Згенерувати набір даних за допомогою означеної функції, з використанням якнайбільшої кількості параметрів. 3. Розмірність набору даних прийняти у вигляді (100000х(30-n)), де n - номер за списком.(1) Здійснити моделювання згенерованого набору даних та візуалізацію результатів. Результати оформити у вигляді файлів:

а) набір даних у форматі .csv;

б) код для формування набору даних у форматі .ipynb;

в) код для моделювання та візуалізації у форматі .ipynb.

Результати викласти у репозиторії GitHub (папка Lab2). Підготуватися до захисту лабораторрної роботи (пояснення коду, відповіді на запитання за темою)

In [13]:
from sklearn import datasets

make_regression():

In [10]:
n_rows = 100000
n_cols = 30-1
data = datasets.make_regression(
    n_samples=n_rows, 
    n_features=n_cols, 
    n_informative=int(n_cols/2), 
    n_targets = int(n_cols/n_cols),
    bias=150,
    effective_rank = None, #сингулярні вектори
    tail_strength = 0.7, #важливість жирного шумового хвоста
    noise = 0.9, #шум
    shuffle = True,
    coef = False,
    random_state=42)

Data:

In [11]:
import pandas as pd
df = pd.DataFrame(data[0])
df = df.add_prefix('x') #adding prefix to column names
df['y'] = data[1]
df.head()

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x20,x21,x22,x23,x24,x25,x26,x27,x28,y
0,0.550355,1.956904,1.655322,0.098064,1.469471,0.383217,0.158035,1.670175,0.112260,0.483383,...,-1.910744,-1.436913,-1.787728,-2.526482,-0.800386,-0.511218,1.493238,-1.230878,0.250911,21.328876
1,0.417331,-0.324924,-0.778990,-2.715421,-1.021756,-0.081104,-0.146577,0.253542,0.094746,0.290659,...,0.517163,-0.241619,-0.963607,0.479437,1.071628,1.274435,-0.429114,0.826262,0.607806,-29.320367
2,-0.137637,1.095394,0.643742,-0.408587,-0.503838,0.633709,0.159339,0.133061,1.766457,0.728787,...,-0.796831,0.203579,-0.297425,1.051333,0.796410,-0.019039,-1.620401,1.096678,-1.417952,163.345543
3,-0.571532,0.881786,0.011437,-1.213074,-1.499535,0.042101,-0.421480,0.241036,0.350995,-0.065269,...,-1.216156,-1.204361,-0.005605,0.149072,-0.946140,-0.776406,0.796164,0.021991,-0.973397,-16.226026
4,0.123441,0.804120,-0.127042,2.080661,-1.651183,-0.526623,0.803081,-0.030294,0.976926,0.164969,...,1.615652,1.840395,-0.399939,-0.895657,-0.464530,0.391511,-0.540588,0.078840,0.521339,331.774061

In [12]:
df.to_csv('data.csv', sep=';', index=False)